import type { Client, Task, TeamMember } from './types';

// DEV: Example clients are kept here as reference. Not used in production.
// To restore demo data, copy this array into mockClients below.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _DEV_mockClients_reference: Client[] = [
  {
    id: '1',
    bedrift: 'Nordisk Helse AS',
    kontaktperson: 'Marte Eriksen',
    epost: 'marte@nordiskhelse.no',
    telefon: '+47 912 34 567',
    nettside: 'nordiskhelse.no',
    bransje: 'Helse & Velvære',
    status: 'Ads live / testing',
    pakke: 'Runde 1 produksjon',
    verdi: 45000,
    ansvarlig: 'Vetle G.',
    prioritet: 'Høy',
    betalingsstatus: 'Betalt',
    kontraktstatus: 'Signert',
    contentMottatt: true,
    adsLive: true,
    sistKontaktet: '2026-04-28',
    nesteAction: 'Send rapport etter 7 dager',
    nesteFrist: '2026-05-05',
    notater: 'Veldig engasjert kunde. Ønsker ukentlige oppdateringer. Produkter selges på nettbutikk og fysisk butikk.',
    invoiceSent: true,
    onboardingComplete: true,
    metaAccessReceived: true,
    brandAssetsReceived: true,
    adsLiveDate: '2026-04-22',
    resultsChecked: false,
    reportSent: false,
    statusChangedAt: '2026-04-28',
    round1Results: 'good',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a1', dato: '2026-04-28', type: 'notat', tekst: 'Ads satt live. Starter med 3 UGC-videoer.', bruker: 'Vetle G.' },
      { id: 'a2', dato: '2026-04-20', type: 'status', tekst: 'Status endret til Ads live / testing', bruker: 'Vetle G.' },
      { id: 'a3', dato: '2026-04-15', type: 'møte', tekst: 'Onboarding-møte gjennomført. Strategi lagt.', bruker: 'Vetle G.' },
    ],
    oppgaver: [
      { id: 't1', tittel: 'Send ukesrapport', klientId: '1', klientNavn: 'Nordisk Helse AS', ansvarlig: 'Vetle G.', frist: '2026-05-05', status: 'Åpen', prioritet: 'Høy' },
    ],
  },
  {
    id: '2',
    bedrift: 'TechFlow Norge',
    kontaktperson: 'Jonas Berg',
    epost: 'jonas@techflow.no',
    telefon: '+47 934 56 789',
    nettside: 'techflow.no',
    bransje: 'SaaS / Tech',
    status: 'Tilbud sendt',
    pakke: 'Prøvepakke',
    verdi: 18000,
    ansvarlig: 'Vetle G.',
    prioritet: 'Høy',
    betalingsstatus: 'Ikke betalt',
    kontraktstatus: 'Sendt',
    contentMottatt: false,
    adsLive: false,
    sistKontaktet: '2026-04-25',
    nesteAction: 'Følg opp tilbud',
    nesteFrist: '2026-05-02',
    notater: 'Interessert i Meta + Google. Har sett resultater fra konkurrenter.',
    invoiceSent: false,
    onboardingComplete: false,
    metaAccessReceived: false,
    brandAssetsReceived: false,
    resultsChecked: false,
    reportSent: false,
    statusChangedAt: '2026-04-25',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a4', dato: '2026-04-25', type: 'epost', tekst: 'Tilbud sendt på e-post.', bruker: 'Vetle G.' },
      { id: 'a5', dato: '2026-04-22', type: 'møte', tekst: 'Videomøte 30 min. Veldig positiv respons.', bruker: 'Vetle G.' },
    ],
    oppgaver: [
      { id: 't2', tittel: 'Følg opp tilbud', klientId: '2', klientNavn: 'TechFlow Norge', ansvarlig: 'Vetle G.', frist: '2026-05-02', status: 'Åpen', prioritet: 'Høy' },
    ],
  },
  {
    id: '3',
    bedrift: 'Fjord Fitness',
    kontaktperson: 'Silje Andersen',
    epost: 'silje@fjordfitness.no',
    telefon: '+47 456 78 901',
    nettside: 'fjordfitness.no',
    bransje: 'Fitness & Trening',
    status: 'Fast kunde / retainer',
    pakke: 'Fast kunde / retainer',
    verdi: 65000,
    ansvarlig: 'Markus S.',
    prioritet: 'Medium',
    betalingsstatus: 'Betalt',
    kontraktstatus: 'Signert',
    contentMottatt: true,
    adsLive: true,
    sistKontaktet: '2026-04-27',
    nesteAction: 'Månedlig strategimøte',
    nesteFrist: '2026-05-10',
    notater: 'Langsiktig kunde. Fornøyd med ROAS på 4.2x. Ønsker å skalere budsjett i mai.',
    invoiceSent: true,
    onboardingComplete: true,
    metaAccessReceived: true,
    brandAssetsReceived: true,
    adsLiveDate: '2026-03-01',
    resultsChecked: true,
    reportSent: true,
    statusChangedAt: '2026-04-01',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a6', dato: '2026-04-27', type: 'notat', tekst: 'ROAS 4.2x siste 30 dager. Kunden er svært fornøyd.', bruker: 'Markus S.' },
      { id: 'a7', dato: '2026-04-01', type: 'status', tekst: 'Månedlig retainer fornyet.', bruker: 'Markus S.' },
    ],
    oppgaver: [
      { id: 't3', tittel: 'Strategimøte mai', klientId: '3', klientNavn: 'Fjord Fitness', ansvarlig: 'Markus S.', frist: '2026-05-10', status: 'Åpen', prioritet: 'Medium' },
    ],
  },
  {
    id: '4',
    bedrift: 'Bolig & Interiør Studio',
    kontaktperson: 'Henrik Dahl',
    epost: 'henrik@bisinterior.no',
    telefon: '+47 987 65 432',
    nettside: 'bisinterior.no',
    bransje: 'Interiør & Bolig',
    status: 'Onboarding',
    pakke: 'Prøvepakke',
    verdi: 18000,
    ansvarlig: 'Vetle G.',
    prioritet: 'Medium',
    betalingsstatus: 'Betalt',
    kontraktstatus: 'Signert',
    contentMottatt: false,
    adsLive: false,
    sistKontaktet: '2026-04-26',
    nesteAction: 'Motta content fra kunde',
    nesteFrist: '2026-05-02',
    notater: 'Har mye produktbilder. Trenger hjelp med UGC-video. Starter med Facebook og Instagram.',
    invoiceSent: true,
    onboardingComplete: false,
    metaAccessReceived: true,
    brandAssetsReceived: false,
    resultsChecked: false,
    reportSent: false,
    statusChangedAt: '2026-04-26',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a8', dato: '2026-04-26', type: 'status', tekst: 'Onboarding startet. Kontrakt signert og betalt.', bruker: 'Vetle G.' },
      { id: 'a9', dato: '2026-04-24', type: 'møte', tekst: 'Onboarding-møte gjennomført via Zoom.', bruker: 'Vetle G.' },
    ],
    oppgaver: [
      { id: 't4', tittel: 'Motta content fra kunde', klientId: '4', klientNavn: 'Bolig & Interiør Studio', ansvarlig: 'Vetle G.', frist: '2026-05-02', status: 'Åpen', prioritet: 'Høy' },
    ],
  },
  {
    id: '5',
    bedrift: 'PetCare Norge',
    kontaktperson: 'Anna Holm',
    epost: 'anna@petcare.no',
    telefon: '+47 776 54 321',
    nettside: 'petcarenorge.no',
    bransje: 'Dyr & Kjæledyr',
    status: 'Lead',
    pakke: '',
    verdi: 0,
    ansvarlig: 'Markus S.',
    prioritet: 'Lav',
    betalingsstatus: 'Ikke betalt',
    kontraktstatus: 'Ikke signert',
    contentMottatt: false,
    adsLive: false,
    sistKontaktet: '2026-04-20',
    nesteAction: 'Book intro-møte',
    nesteFrist: '2026-05-03',
    notater: 'Kom inn via referanse fra Fjord Fitness. Selger hundemat og tilbehør på nett.',
    invoiceSent: false,
    onboardingComplete: false,
    metaAccessReceived: false,
    brandAssetsReceived: false,
    resultsChecked: false,
    reportSent: false,
    statusChangedAt: '2026-04-20',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a10', dato: '2026-04-20', type: 'notat', tekst: 'Innkommende lead via referanse. Sendt velkomstmelding.', bruker: 'Markus S.' },
    ],
    oppgaver: [
      { id: 't5', tittel: 'Book intro-møte', klientId: '5', klientNavn: 'PetCare Norge', ansvarlig: 'Markus S.', frist: '2026-05-03', status: 'Åpen', prioritet: 'Lav' },
    ],
  },
  {
    id: '6',
    bedrift: 'Klima Klær AS',
    kontaktperson: 'Tor Bakken',
    epost: 'tor@klimaklaer.no',
    telefon: '+47 654 32 109',
    nettside: 'klimaklaer.no',
    bransje: 'Mote & Klær',
    status: 'Runde 2',
    pakke: 'Runde 2',
    verdi: 32000,
    ansvarlig: 'Vetle G.',
    prioritet: 'Høy',
    betalingsstatus: 'Betalt',
    kontraktstatus: 'Signert',
    contentMottatt: true,
    adsLive: true,
    sistKontaktet: '2026-04-29',
    nesteAction: 'Optimalisere kampanjer basert på data',
    nesteFrist: '2026-05-06',
    notater: 'Runde 1 gikk bra. ROAS 3.1x. Nå skalerer vi med Runde 2-pakken.',
    invoiceSent: true,
    onboardingComplete: true,
    metaAccessReceived: true,
    brandAssetsReceived: true,
    adsLiveDate: '2026-04-15',
    resultsChecked: true,
    reportSent: false,
    statusChangedAt: '2026-04-25',
    round1Results: 'great',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a11', dato: '2026-04-29', type: 'notat', tekst: 'Runde 2 startet. Nye annonsegrupper opprettet.', bruker: 'Vetle G.' },
      { id: 'a12', dato: '2026-04-15', type: 'status', tekst: 'Runde 1 avsluttet med ROAS 3.1x.', bruker: 'Vetle G.' },
    ],
    oppgaver: [
      { id: 't6', tittel: 'Kampanjeoptimalisering uke 2', klientId: '6', klientNavn: 'Klima Klær AS', ansvarlig: 'Vetle G.', frist: '2026-05-06', status: 'Pågår', prioritet: 'Høy' },
    ],
  },
  {
    id: '7',
    bedrift: 'Oslo Kaffebar',
    kontaktperson: 'Ingrid Lie',
    epost: 'ingrid@oslokaffebar.no',
    telefon: '+47 543 21 098',
    nettside: 'oslokaffebar.no',
    bransje: 'Mat & Drikke',
    status: 'Møte booket',
    pakke: '',
    verdi: 0,
    ansvarlig: 'Markus S.',
    prioritet: 'Medium',
    betalingsstatus: 'Ikke betalt',
    kontraktstatus: 'Ikke signert',
    contentMottatt: false,
    adsLive: false,
    sistKontaktet: '2026-04-28',
    nesteAction: 'Gjennomfør møte 2. mai',
    nesteFrist: '2026-05-02',
    notater: 'Kaffebar med nettbutikk. Interessert i lokale annonser + nettbutikk-kampanjer.',
    invoiceSent: false,
    onboardingComplete: false,
    metaAccessReceived: false,
    brandAssetsReceived: false,
    resultsChecked: false,
    reportSent: false,
    statusChangedAt: '2026-04-28',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a13', dato: '2026-04-28', type: 'møte', tekst: 'Møte booket for 2. mai kl. 10:00.', bruker: 'Markus S.' },
      { id: 'a14', dato: '2026-04-25', type: 'epost', tekst: 'Intro-e-post sendt med info om Klyr.', bruker: 'Markus S.' },
    ],
    oppgaver: [
      { id: 't7', tittel: 'Forbered presentasjon til møte', klientId: '7', klientNavn: 'Oslo Kaffebar', ansvarlig: 'Markus S.', frist: '2026-05-01', status: 'Åpen', prioritet: 'Medium' },
    ],
  },
  {
    id: '8',
    bedrift: 'Solenergi Solutions',
    kontaktperson: 'Per Nilsen',
    epost: 'per@solenergisolutions.no',
    telefon: '+47 432 10 987',
    nettside: 'solenergisolutions.no',
    bransje: 'Energi & Teknologi',
    status: 'Pauset',
    pakke: 'Fast kunde / retainer',
    verdi: 55000,
    ansvarlig: 'Vetle G.',
    prioritet: 'Medium',
    betalingsstatus: 'Venter',
    kontraktstatus: 'Signert',
    contentMottatt: true,
    adsLive: false,
    sistKontaktet: '2026-04-10',
    nesteAction: 'Avklare videre samarbeid i juni',
    nesteFrist: null,
    notater: 'Pauset på grunn av intern omstrukturering. Forventer å gjenoppta i juni.',
    invoiceSent: true,
    onboardingComplete: true,
    metaAccessReceived: true,
    brandAssetsReceived: true,
    resultsChecked: true,
    reportSent: true,
    statusChangedAt: '2026-04-10',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a15', dato: '2026-04-10', type: 'notat', tekst: 'Kunde ønsker pause til juni. Interne endringer.', bruker: 'Vetle G.' },
      { id: 'a16', dato: '2026-04-10', type: 'status', tekst: 'Status endret til Pauset.', bruker: 'Vetle G.' },
    ],
    oppgaver: [],
  },
  {
    id: '9',
    bedrift: 'MindBody Studio',
    kontaktperson: 'Camilla Voss',
    epost: 'camilla@mindbodystudio.no',
    telefon: '+47 321 09 876',
    nettside: 'mindbodystudio.no',
    bransje: 'Helse & Velvære',
    status: 'Prøvepakke betalt',
    pakke: 'Prøvepakke',
    verdi: 18000,
    ansvarlig: 'Markus S.',
    prioritet: 'Høy',
    betalingsstatus: 'Betalt',
    kontraktstatus: 'Signert',
    contentMottatt: false,
    adsLive: false,
    sistKontaktet: '2026-04-27',
    nesteAction: 'Kickoff-møte og content-brief',
    nesteFrist: '2026-05-01',
    notater: 'Yoga- og meditasjonssenter. Vil kjøre Meta-annonser mot lokal målgruppe.',
    invoiceSent: false,
    onboardingComplete: false,
    metaAccessReceived: false,
    brandAssetsReceived: false,
    resultsChecked: false,
    reportSent: false,
    statusChangedAt: '2026-04-27',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a17', dato: '2026-04-27', type: 'status', tekst: 'Prøvepakke betalt. Onboarding startes.', bruker: 'Markus S.' },
    ],
    oppgaver: [
      { id: 't8', tittel: 'Send content-brief', klientId: '9', klientNavn: 'MindBody Studio', ansvarlig: 'Markus S.', frist: '2026-05-01', status: 'Åpen', prioritet: 'Høy' },
    ],
  },
  {
    id: '10',
    bedrift: 'Byggmester Larsen',
    kontaktperson: 'Rune Larsen',
    epost: 'rune@byggmesterlarsen.no',
    telefon: '+47 210 98 765',
    nettside: 'byggmesterlarsen.no',
    bransje: 'Bygg & Anlegg',
    status: 'Kontaktet',
    pakke: '',
    verdi: 0,
    ansvarlig: 'Vetle G.',
    prioritet: 'Lav',
    betalingsstatus: 'Ikke betalt',
    kontraktstatus: 'Ikke signert',
    contentMottatt: false,
    adsLive: false,
    sistKontaktet: '2026-04-18',
    nesteAction: 'Send case study og tilbud',
    nesteFrist: '2026-05-05',
    notater: 'Håndverker med lokalt fokus. Interessert i å generere lokale leads.',
    invoiceSent: false,
    onboardingComplete: false,
    metaAccessReceived: false,
    brandAssetsReceived: false,
    resultsChecked: false,
    reportSent: false,
    statusChangedAt: '2026-04-18',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a18', dato: '2026-04-18', type: 'epost', tekst: 'Intro-e-post sendt. Avventer svar.', bruker: 'Vetle G.' },
    ],
    oppgaver: [
      { id: 't9', tittel: 'Send case study til Larsen', klientId: '10', klientNavn: 'Byggmester Larsen', ansvarlig: 'Vetle G.', frist: '2026-05-05', status: 'Åpen', prioritet: 'Lav' },
    ],
  },
  {
    id: '11',
    bedrift: 'Eventbyrå Spark',
    kontaktperson: 'Nina Strand',
    epost: 'nina@eventbyraspark.no',
    telefon: '+47 109 87 654',
    nettside: 'eventbyraspark.no',
    bransje: 'Event & Underholdning',
    status: 'Runde 1 produksjon',
    pakke: 'Runde 1 produksjon',
    verdi: 28000,
    ansvarlig: 'Markus S.',
    prioritet: 'Medium',
    betalingsstatus: 'Betalt',
    kontraktstatus: 'Signert',
    contentMottatt: true,
    adsLive: false,
    sistKontaktet: '2026-04-29',
    nesteAction: 'Ferdigstill annonsekreativer',
    nesteFrist: '2026-05-04',
    notater: 'Eventbyrå som ønsker å generere bookings via Meta. Har levert godt bildemateriale.',
    invoiceSent: true,
    onboardingComplete: true,
    metaAccessReceived: true,
    brandAssetsReceived: true,
    resultsChecked: false,
    reportSent: false,
    statusChangedAt: '2026-04-22',
    round1Results: 'unknown',
    offboardingEmailSent: false,
    finalInvoiceSent: false,
    deliveryCompleted: false,
    aktivitetslogg: [
      { id: 'a19', dato: '2026-04-29', type: 'notat', tekst: 'Content mottatt. Produksjon av annonser starter.', bruker: 'Markus S.' },
      { id: 'a20', dato: '2026-04-22', type: 'status', tekst: 'Status endret til Runde 1 produksjon.', bruker: 'Markus S.' },
    ],
    oppgaver: [
      { id: 't10', tittel: 'Ferdigstill annonsekreativer', klientId: '11', klientNavn: 'Eventbyrå Spark', ansvarlig: 'Markus S.', frist: '2026-05-04', status: 'Pågår', prioritet: 'Medium' },
    ],
  },
];

export const mockClients: Client[] = [];

export const mockTasks: Task[] = mockClients.flatMap((c) => c.oppgaver);

export const mockTeam: TeamMember[] = [
  {
    id: 'vetle',
    navn: 'Vetle G.',
    initialer: 'VG',
    rolle: 'Account Manager',
    epost: 'vetle@klyr.no',
    notificationsEnabled: true,
    notificationTypes: {
      overdueAlerts: true,
      missingActions: true,
      invoiceReminders: true,
      followUpReminders: true,
      onboardingReminders: true,
      reportReminders: true,
    },
  },
  {
    id: 'markus',
    navn: 'Markus S.',
    initialer: 'MS',
    rolle: 'Media Buyer / Strategist',
    epost: 'markus@klyr.no',
    notificationsEnabled: true,
    notificationTypes: {
      overdueAlerts: true,
      missingActions: true,
      invoiceReminders: true,
      followUpReminders: true,
      onboardingReminders: true,
      reportReminders: true,
    },
  },
];

// Package data has moved to lib/packages.ts → KLYR_PACKAGES.
